<script src="js/jquery.maskedinput.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        //Mascara de Data
        $('.date').mask('99/99/9999');
    });
</script>

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-6">
            <h2>Gerenciar Vendas</h2>
        </div>
        <div class="col-6 text-end">
            <a href="?page=venda" class="text-success" title="Cadastrar Novo">
                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <hr>

    <div class="row">
        <form action="" method="post">
            <div class="row">
                <div class="col-md-3 col-6">
                    <label for="de">Data de:</label>
                    <input type="text" id="de" name="de" value="{de}" class="form-control date" />
                </div>
                <div class="col-md-3 col-6">
                    <label for="ate">Data até:</label>
                    <input type="text" id="ate" name="ate" value="{ate}" class="form-control date" />
                </div>

                <div class="col-md-1 col-6" style="padding-top: 25px;">
                    <input type="submit" value="Buscar" class="btn btn-success" title="Buscar" />
                </div>
            </div>
        </form>
    </div>
</div>

<table class="table table-striped table-bordered table-responsive mt-3">
    <thead>
        <th>
            Data
        </th>
        <th>
            Obs
        </th>
        <th>
            Valor Total Itens
        </th>
        <th>
            Valor Total Imposto
        </th>
        <th>
            Mais Detalhes
        </th>
        
    </thead>
    {table_dados}
</table>

{paginacao}