<div class="container">
    <div class="alert alert-danger text-center" style="display:{display};">
        Usuario ou Senha Incorretos
    </div>
    <form class="form-signin" action="#" method="post">
        <h2 class="form-signin-heading">Gestão de Locações</h2>
        <div>
            <label for="email" class="sr-only">Email</label>
            <input type="text" name="email" id="email" class="form-control" placeholder="Digite o Email" value="{email}" required autofocus>
        </div>
        <div>
            <label for="senha" class="sr-only">Senha</label>
            <input type="password" name="senha" id="senha" class="form-control" placeholder="Digite a senha" value="{senha}" required>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Logar">
    </form>

</div>