<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-6">
            <h2>Deletar Categoria de Produto</h2>
        </div>
        <div class="col-6 text-end">
            <a href="?page={page}" class="text-success" title="Cadastrar Novo">
                <i class="fa fa-arrow-left fa-3x" aria-hidden="true" title="VOLTAR"></i>
            </a>
        </div>
    </div>
    <hr>

    <div class="row text-center">
        <h3 class="text-center text-danger">Não foi possivel excluir a categoria pois existe Produtos Vinculados</h3>
        
    </div>
</div>