<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-6">
            <h2>Gerenciar Produto</h2>
        </div>
        <div class="col-6 text-end">
            <a href="?page={page}&action=cadastrar" class="text-success" title="Cadastrar Novo">
                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <hr>

    <div class="row">
        <form action="" method="post">
            <div class="row">
                <div class="col-md-3 col-6">
                    <label for="nome">Nome:</label>
                    <input type="text" id="nome" name="nome" value="{nome}" class="form-control" />
                </div>

                <div class="col-md-1 col-6" style="padding-top: 25px;">
                    <input type="submit" value="Buscar" class="btn btn-success" title="Buscar" />
                </div>
            </div>
        </form>
    </div>
</div>

<table class="table table-striped table-bordered table-responsive mt-3">
    <thead>
        <th>
            Categoria
        </th>
        <th>
            Nome
        </th>
        <th>
            Valor
        </th>
        <th>
            Status
        </th>
        
        <th>
            Ações
        </th>
    </thead>
    {table_dados}
</table>

{paginacao}