<script src="js/jquery.priceformat.min.js" type="text/javascript"></script>
<script src="js/bootbox.all.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#produto_valor').priceFormat({
            prefix: '',
            centsSeparator: ',',
            thousandsSeparator: '.'
        });

        $("#add-item").click(function() {
            $('<div class="card mt-2 mb-2">' + $('.card-copy').html() + '</div>').insertBefore('.box-add');
        });
        $(document).on("click", '.btn-exclui-item', function() {
            //$(this).parent().parent()

            if ($(this).parent().parent().parent().attr('rel') == 'principal') {
                alertcustom('Primeiro Produto não é possivel excluir')
            } else {
                $(this).parent().parent().parent().remove();

            }
        });

        //Faz o envio
        $('form').submit(function(e) {
            // ;;btnloading('loading');
            e.preventDefault;
            $.ajax({
                url: '?page={page}&action=cadastrar',
                type: 'POST',
                data: $(this).serialize(),
                success: function(data) {
                    // btnloading('reset');

                    arr = JSON.parse(data);
                    if (arr['status'] === '1') {
                        alertcustom(arr['mensagem'], 'true');
                    } else {
                        alertcustom(arr['mensagem']);
                    }

                },
                error: function(xhr, err) {
                    alert('Error');
                    btnloading('reset');
                }
            });
            return false;
        });

       
    });

    function alertcustom(text, redirect = false) {
        bootbox.alert({
            message: text,
            centerVertical: true,
            callback: function() {
                if (redirect != false) {
                    window.location.href = "?page={page}";
                }
            }
        });
    }
</script>

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-6">
            <h2>Realizar Venda</h2>
        </div>
        <div class="col-6 text-end">

        </div>
    </div>
    <hr>

    <!-- <div class="alert alert-warning text-center" style="display:{displayvalid};">
        {textvalid}
    </div> -->
    <div class="container mb-5">
        <form action="" method="POST" class="row">
            <input type="hidden" name="produto_id" value="{produto_id}">
            <div class="card card-copy mt-2 mb-2" rel="principal">
                <div class="card-body row">
                    <div class="mb-3 col-6">
                        <label for="produto_id" class="form-label">Produto</label>
                        <select class="form-control form-select" name='produto_id[]' required>
                            <option value="">Selecione o Produto</option>
                            {optioncategoria}
                        </select>
                    </div>

                    <div class="mb-3 col-5">
                        <label for="produto_qtd" class="form-label">Quantidade</label>
                        <input type="number" class="form-control" name="produto_qtd[]" id="produto_qtd" value="{produto_qtd}" required>
                    </div>
                    <div class="col-1 text-center pt-3">
                        <a class="btn-exclui-item"><i class="fa fa-trash fa-3x text-danger"></i></a>
                    </div>
                </div>
            </div>
            <div class="text-center mt-2 box-add">
                <button class="btn btn-info col-4" type="button" id="add-item">Adicionar Item</button>
            </div>
            <div class="mb-3 col-12">
                <label for="venda_obs" class="form-label">Observação</label>
                <textarea type="text" class="form-control" name="venda_obs" id="venda_obs">{venda_obs}</textarea>
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>